### PR TITLE
MS-13: Rename 'Mendelian Search' to 'Cohort Discovery Tool'

### PR DESCRIPTION
**Pull request by sh-ura**

### CODE REVIEW

**Review by marta- — CHANGES_REQUESTED** [review]
Did you forget to commit some changes? This won't change the URL and a lot of things will stop functioning because there are references to non-existing documents. As long as the name of the document is `MendelianResults.xml`, the URL will be `.../MendelianResults`. You need to rename the document.

**Comment by marta-** [comment]
Also the text modifications are incomplete, please see the comments on https://phenotips.atlassian.net/browse/MS-13 for additional changes suggested by Brittney.

**Comment by katpavlova** [comment]
@marta- I will implement Brittney's additional requests, but I tested both of these commits and the URL definitely comes out as .../CohortDiscoveryResults.

**Comment by sh-ura** [comment]
@marta- I will implement Brittney's requests, sorry for not having seen them. Also I did test these commits and the URL was coming out as `.../CohortDiscoveryResults`, so I pushed it with the least possible amount of code changes necessary to implement the URL change. But I can see how that will likely result in bugs in the future so I will change the whole xml file to use `CohortDiscoveryResults`. Thanks for the feedback.

**Comment by sh-ura** [comment]
@marta- Both comments have been addressed in the two newest commits.

**Review by veronikaslc — APPROVED** [review]

**Pull request merged**
